
name: Android CI2

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Pull LFS files
      run: git lfs pull

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: "Get Short SHA"
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: "Get Version"
      run: echo "VERSION=$(echo $(cat app/build.gradle.kts | grep versionName | cut -d "=" -f 2 | sed "s/\"//g"))" >> $GITHUB_ENV

    - name: "List files"
      run: |
        ls -la app/src/main/assets

    - name: "Create Release"
      uses: softprops/action-gh-release@v2
      with:
        name: "winlator_bionic ${{ env.VERSION }}-(git-${{ env.SHORT_SHA }})"
        tag_name: ${{ env.SHORT_SHA }}
        prerelease: true
        files: ./app/build/outputs/apk/debug/app-debug.apk
